export const cardsData = [
  {
    type: "Resort",
    id: 1,
    placeType: "Ресторан",
    name: "Ресторан La Cucina",
    description: "Итальянская кухня в уютной атмосфере",
    photos: ["https://example.com/images/cafe-2.jpg"],
  },
  {
    type: "Hub",
    id: 2,
    placeType: "Кафе",
    name: "Кафе Coffee Time",
    description: "Ароматный кофе и вкусные десерты",
    photos: ["https://example.com/images/cafe-2.jpg"],
  },
  {
    type: "Pitstop",
    id: 3,
    placeType: "Музей",
    name: "Музей искусств",
    description: "Коллекция шедевров мировой живописи",
    photos: ["https://example.com/images/cafe-2.jpg"],
  },
  {
    type: "Pitstop",
    id: 4,
    placeType: "Парк",
    name: "Центральный парк",
    description: "Живописные аллеи, фонтаны и детские площадки",
    photos: ["https://example.com/images/cafe-2.jpg"],
  },
  {
    type: "Hub",
    id: 5,
    placeType: "Кинотеатр",
    name: "Киноцентр Cosmos",
    description: "Новые фильмы на большом экране",
    photos: ["https://example.com/images/cafe-2.jpg"],
  },
];
