#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"

requiredPattern="^(feat|fix|style|refactor|perf|test|ci|chore|docs): [a-zA-Z ,:;.-/]+$"

if [[ $message =~ $requiredPattern ]]; then
 echo "Nice commit!"
else
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "heading: commit message in english"
  echo "Allowed headings: feat, fix, style, refactor, perf, test, ci, chore, docs"
  echo "Allowed signs in message: , : . ; - /"
  echo "Example: feat: add something in App.tsx"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi